### ISSUE TITLE
Change position of notify to top

### ISSUE THREAD

**Issue by victorighalo** [gleissonmattos/alertui-js#1]
Is there an option to change the notify position to the top?

**Comment by gleissonmattos** [comment]
Hey. Sorry I'm late. So ... At the moment it is not possible to change the position of notify.
You are in some need of it right now. I can include it in the list to implement

**Comment by victorighalo** [comment]
Yes. I am in need of it now. I use it in all my applications and would not want to use any other. It will be nice if it can have more features, such as position and adding toasts. Thanks. I will also see if i have free time to make contributions.

**Comment by gleissonmattos** [comment]
Alright, victor. I will implement and soon I will be updating a version including fixes. A hug.
